# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design1.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(457, 232)
        MainWindow.setMinimumSize(QtCore.QSize(457, 232))
        MainWindow.setMaximumSize(QtCore.QSize(457, 232))
        MainWindow.setFocusPolicy(QtCore.Qt.TabFocus)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/data/app.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.okay = QtWidgets.QPushButton(self.centralwidget)
        self.okay.setGeometry(QtCore.QRect(40, 180, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.okay.setFont(font)
        self.okay.setFocusPolicy(QtCore.Qt.NoFocus)
        self.okay.setObjectName("okay")
        self.cancel = QtWidgets.QPushButton(self.centralwidget)
        self.cancel.setGeometry(QtCore.QRect(240, 180, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.cancel.setFont(font)
        self.cancel.setFocusPolicy(QtCore.Qt.NoFocus)
        self.cancel.setObjectName("cancel")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(30, 20, 401, 151))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setContentsMargins(35, -1, -1, -1)
        self.formLayout.setHorizontalSpacing(6)
        self.formLayout.setVerticalSpacing(0)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label)
        self.login = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.login.setFont(font)
        self.login.setStyleSheet("color: rgb(0, 170, 0);")
        self.login.setObjectName("login")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.login)
        self.login_edit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.login_edit.sizePolicy().hasHeightForWidth())
        self.login_edit.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.login_edit.setFont(font)
        self.login_edit.setInputMask("")
        self.login_edit.setMaxLength(32767)
        self.login_edit.setFrame(True)
        self.login_edit.setObjectName("login_edit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.login_edit)
        self.verticalLayout_2.addLayout(self.formLayout)
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setSizeConstraint(QtWidgets.QLayout.SetMinAndMaxSize)
        self.formLayout_2.setFieldGrowthPolicy(QtWidgets.QFormLayout.ExpandingFieldsGrow)
        self.formLayout_2.setLabelAlignment(QtCore.Qt.AlignCenter)
        self.formLayout_2.setFormAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.formLayout_2.setContentsMargins(25, -1, -1, -1)
        self.formLayout_2.setHorizontalSpacing(6)
        self.formLayout_2.setVerticalSpacing(0)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_3.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.password_edit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.password_edit.setFont(font)
        self.password_edit.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.password_edit.setInputMethodHints(QtCore.Qt.ImhHiddenText|QtCore.Qt.ImhNoAutoUppercase|QtCore.Qt.ImhNoPredictiveText|QtCore.Qt.ImhSensitiveData)
        self.password_edit.setInputMask("")
        self.password_edit.setText("")
        self.password_edit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password_edit.setObjectName("password_edit")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.password_edit)
        self.password = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.password.setFont(font)
        self.password.setStyleSheet("color: rgb(0, 170, 0);")
        self.password.setObjectName("password")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.password)
        self.verticalLayout_2.addLayout(self.formLayout_2)
        self.formLayout_3 = QtWidgets.QFormLayout()
        self.formLayout_3.setHorizontalSpacing(6)
        self.formLayout_3.setVerticalSpacing(0)
        self.formLayout_3.setObjectName("formLayout_3")
        self.label_5 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.repeat_password_edit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.repeat_password_edit.setFont(font)
        self.repeat_password_edit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.repeat_password_edit.setObjectName("repeat_password_edit")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.repeat_password_edit)
        self.repeat_password = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.repeat_password.setFont(font)
        self.repeat_password.setStyleSheet("color: rgb(0, 170, 0);")
        self.repeat_password.setWordWrap(False)
        self.repeat_password.setObjectName("repeat_password")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.repeat_password)
        self.verticalLayout_2.addLayout(self.formLayout_3)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Регистрация"))
        self.okay.setText(_translate("MainWindow", "Зарегистрировать"))
        self.cancel.setText(_translate("MainWindow", "Отмена"))
        self.label.setText(_translate("MainWindow", "Логин"))
        self.login.setText(_translate("MainWindow", "Проверено"))
        self.label_3.setText(_translate("MainWindow", "Пароль"))
        self.password.setText(_translate("MainWindow", "Соответствует"))
        self.label_5.setText(_translate("MainWindow", "Повторите"))
        self.repeat_password.setText(_translate("MainWindow", "Совпадает"))

import resurs_rc
