# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design2.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.WindowModal)
        MainWindow.resize(686, 343)
        MainWindow.setMinimumSize(QtCore.QSize(686, 343))
        MainWindow.setMaximumSize(QtCore.QSize(686, 343))
        MainWindow.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/data/app.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setFocusPolicy(QtCore.Qt.TabFocus)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(-40, 10, 731, 291))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/data/main.png"))
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 686, 21))
        self.menuBar.setObjectName("menuBar")
        self.menu = QtWidgets.QMenu(self.menuBar)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(self.menuBar)
        self.menu_2.setObjectName("menu_2")
        self.menu_3 = QtWidgets.QMenu(self.menuBar)
        self.menu_3.setObjectName("menu_3")
        self.menu_4 = QtWidgets.QMenu(self.menuBar)
        self.menu_4.setObjectName("menu_4")
        self.menu_5 = QtWidgets.QMenu(self.menuBar)
        self.menu_5.setObjectName("menu_5")
        self.menu_6 = QtWidgets.QMenu(self.menuBar)
        self.menu_6.setObjectName("menu_6")
        self.menu_7 = QtWidgets.QMenu(self.menuBar)
        self.menu_7.setEnabled(True)
        self.menu_7.setObjectName("menu_7")
        self.menu_8 = QtWidgets.QMenu(self.menuBar)
        self.menu_8.setObjectName("menu_8")
        MainWindow.setMenuBar(self.menuBar)
        self.write = QtWidgets.QAction(MainWindow)
        self.write.setObjectName("write")
        self.use_old = QtWidgets.QAction(MainWindow)
        self.use_old.setObjectName("use_old")
        self.copy_from_imput = QtWidgets.QAction(MainWindow)
        self.copy_from_imput.setObjectName("copy_from_imput")
        self.open_input = QtWidgets.QAction(MainWindow)
        self.open_input.setObjectName("open_input")
        self.clear_input = QtWidgets.QAction(MainWindow)
        self.clear_input.setObjectName("clear_input")
        self.check_all = QtWidgets.QAction(MainWindow)
        self.check_all.setObjectName("check_all")
        self.open_output = QtWidgets.QAction(MainWindow)
        self.open_output.setObjectName("open_output")
        self.clear_output = QtWidgets.QAction(MainWindow)
        self.clear_output.setObjectName("clear_output")
        self.resend = QtWidgets.QAction(MainWindow)
        self.resend.setObjectName("resend")
        self.open_bl = QtWidgets.QAction(MainWindow)
        self.open_bl.setObjectName("open_bl")
        self.add_to_bl = QtWidgets.QAction(MainWindow)
        self.add_to_bl.setObjectName("add_to_bl")
        self.delete_from_bl = QtWidgets.QAction(MainWindow)
        self.delete_from_bl.setObjectName("delete_from_bl")
        self.clear_bl = QtWidgets.QAction(MainWindow)
        self.clear_bl.setObjectName("clear_bl")
        self.open_trash = QtWidgets.QAction(MainWindow)
        self.open_trash.setObjectName("open_trash")
        self.clear_trash = QtWidgets.QAction(MainWindow)
        self.clear_trash.setObjectName("clear_trash")
        self.open_other = QtWidgets.QAction(MainWindow)
        self.open_other.setObjectName("open_other")
        self.add_other = QtWidgets.QAction(MainWindow)
        self.add_other.setObjectName("add_other")
        self.delete_other = QtWidgets.QAction(MainWindow)
        self.delete_other.setObjectName("delete_other")
        self.update_start = QtWidgets.QAction(MainWindow)
        self.update_start.setObjectName("update_start")
        self.updated_is = QtWidgets.QAction(MainWindow)
        self.updated_is.setObjectName("updated_is")
        self.menu.addAction(self.open_input)
        self.menu.addAction(self.clear_input)
        self.menu.addAction(self.check_all)
        self.menu_2.addAction(self.open_output)
        self.menu_2.addAction(self.resend)
        self.menu_2.addAction(self.clear_output)
        self.menu_3.addAction(self.write)
        self.menu_3.addAction(self.use_old)
        self.menu_3.addAction(self.copy_from_imput)
        self.menu_4.addAction(self.open_bl)
        self.menu_4.addAction(self.add_to_bl)
        self.menu_4.addAction(self.delete_from_bl)
        self.menu_4.addAction(self.clear_bl)
        self.menu_5.addAction(self.open_trash)
        self.menu_5.addAction(self.clear_trash)
        self.menu_6.addAction(self.open_other)
        self.menu_6.addAction(self.add_other)
        self.menu_6.addAction(self.delete_other)
        self.menu_8.addAction(self.update_start)
        self.menu_8.addAction(self.updated_is)
        self.menuBar.addAction(self.menu_3.menuAction())
        self.menuBar.addAction(self.menu.menuAction())
        self.menuBar.addAction(self.menu_2.menuAction())
        self.menuBar.addAction(self.menu_4.menuAction())
        self.menuBar.addAction(self.menu_5.menuAction())
        self.menuBar.addAction(self.menu_6.menuAction())
        self.menuBar.addAction(self.menu_7.menuAction())
        self.menuBar.addAction(self.menu_8.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Quinkokolobicky - "))
        self.menu.setTitle(_translate("MainWindow", "Входящие"))
        self.menu_2.setTitle(_translate("MainWindow", "Исходящие"))
        self.menu_3.setTitle(_translate("MainWindow", "Новое письмо"))
        self.menu_4.setTitle(_translate("MainWindow", "Спам"))
        self.menu_5.setTitle(_translate("MainWindow", "Корзина"))
        self.menu_6.setTitle(_translate("MainWindow", "Другие папки"))
        self.menu_7.setTitle(_translate("MainWindow", "Настройки аккаунта"))
        self.menu_8.setTitle(_translate("MainWindow", "Обновить"))
        self.write.setText(_translate("MainWindow", "Написать"))
        self.use_old.setText(_translate("MainWindow", "Использовать шаблон"))
        self.copy_from_imput.setText(_translate("MainWindow", "Скопировать из исходящих"))
        self.open_input.setText(_translate("MainWindow", "Открыть"))
        self.clear_input.setText(_translate("MainWindow", "Очистить"))
        self.check_all.setText(_translate("MainWindow", "Отметить как прочтенное"))
        self.open_output.setText(_translate("MainWindow", "Открыть"))
        self.clear_output.setText(_translate("MainWindow", "Очистить"))
        self.resend.setText(_translate("MainWindow", "Переслать"))
        self.open_bl.setText(_translate("MainWindow", "Открыть"))
        self.add_to_bl.setText(_translate("MainWindow", "Добавить в ЧС нового абонента"))
        self.delete_from_bl.setText(_translate("MainWindow", "Удалить из ЧС абонента"))
        self.clear_bl.setText(_translate("MainWindow", "Очистить"))
        self.open_trash.setText(_translate("MainWindow", "Открыть"))
        self.clear_trash.setText(_translate("MainWindow", "Очистить"))
        self.open_other.setText(_translate("MainWindow", "Открыть"))
        self.add_other.setText(_translate("MainWindow", "Добавить новую папку"))
        self.delete_other.setText(_translate("MainWindow", "Удалить папку"))
        self.update_start.setText(_translate("MainWindow", "Запуск обновления"))
        self.updated_is.setText(_translate("MainWindow", "Проверка на новую версию"))

import resurs_rc
