# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design2.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.WindowModal)
        MainWindow.resize(686, 343)
        MainWindow.setMinimumSize(QtCore.QSize(686, 343))
        MainWindow.setMaximumSize(QtCore.QSize(686, 343))
        MainWindow.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/data/app.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setFocusPolicy(QtCore.Qt.TabFocus)
        self.centralwidget.setObjectName("centralwidget")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 686, 21))
        self.menuBar.setObjectName("menuBar")
        self.menu = QtWidgets.QMenu(self.menuBar)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(self.menuBar)
        self.menu_2.setObjectName("menu_2")
        self.menu_3 = QtWidgets.QMenu(self.menuBar)
        self.menu_3.setObjectName("menu_3")
        self.menu_4 = QtWidgets.QMenu(self.menuBar)
        self.menu_4.setObjectName("menu_4")
        self.menu_5 = QtWidgets.QMenu(self.menuBar)
        self.menu_5.setObjectName("menu_5")
        self.menu_6 = QtWidgets.QMenu(self.menuBar)
        self.menu_6.setObjectName("menu_6")
        self.menu_7 = QtWidgets.QMenu(self.menuBar)
        self.menu_7.setObjectName("menu_7")
        self.menu_8 = QtWidgets.QMenu(self.menuBar)
        self.menu_8.setObjectName("menu_8")
        MainWindow.setMenuBar(self.menuBar)
        self.action = QtWidgets.QAction(MainWindow)
        self.action.setObjectName("action")
        self.action_2 = QtWidgets.QAction(MainWindow)
        self.action_2.setObjectName("action_2")
        self.action_3 = QtWidgets.QAction(MainWindow)
        self.action_3.setObjectName("action_3")
        self.action_4 = QtWidgets.QAction(MainWindow)
        self.action_4.setObjectName("action_4")
        self.action_5 = QtWidgets.QAction(MainWindow)
        self.action_5.setObjectName("action_5")
        self.action_6 = QtWidgets.QAction(MainWindow)
        self.action_6.setObjectName("action_6")
        self.action_7 = QtWidgets.QAction(MainWindow)
        self.action_7.setObjectName("action_7")
        self.action_8 = QtWidgets.QAction(MainWindow)
        self.action_8.setObjectName("action_8")
        self.action_9 = QtWidgets.QAction(MainWindow)
        self.action_9.setObjectName("action_9")
        self.action_12 = QtWidgets.QAction(MainWindow)
        self.action_12.setObjectName("action_12")
        self.action_13 = QtWidgets.QAction(MainWindow)
        self.action_13.setObjectName("action_13")
        self.action_14 = QtWidgets.QAction(MainWindow)
        self.action_14.setObjectName("action_14")
        self.action_15 = QtWidgets.QAction(MainWindow)
        self.action_15.setObjectName("action_15")
        self.action_16 = QtWidgets.QAction(MainWindow)
        self.action_16.setObjectName("action_16")
        self.action_17 = QtWidgets.QAction(MainWindow)
        self.action_17.setObjectName("action_17")
        self.action_18 = QtWidgets.QAction(MainWindow)
        self.action_18.setObjectName("action_18")
        self.action_19 = QtWidgets.QAction(MainWindow)
        self.action_19.setObjectName("action_19")
        self.action_20 = QtWidgets.QAction(MainWindow)
        self.action_20.setObjectName("action_20")
        self.update_start = QtWidgets.QAction(MainWindow)
        self.update_start.setObjectName("update_start")
        self.updated_is = QtWidgets.QAction(MainWindow)
        self.updated_is.setObjectName("updated_is")
        self.menu.addAction(self.action_4)
        self.menu.addAction(self.action_5)
        self.menu.addAction(self.action_6)
        self.menu_2.addAction(self.action_7)
        self.menu_2.addAction(self.action_9)
        self.menu_2.addAction(self.action_8)
        self.menu_3.addAction(self.action)
        self.menu_3.addAction(self.action_2)
        self.menu_3.addAction(self.action_3)
        self.menu_4.addAction(self.action_12)
        self.menu_4.addAction(self.action_13)
        self.menu_4.addAction(self.action_14)
        self.menu_4.addAction(self.action_15)
        self.menu_5.addAction(self.action_16)
        self.menu_5.addAction(self.action_17)
        self.menu_6.addAction(self.action_18)
        self.menu_6.addAction(self.action_19)
        self.menu_6.addAction(self.action_20)
        self.menu_8.addAction(self.update_start)
        self.menu_8.addAction(self.updated_is)
        self.menuBar.addAction(self.menu_3.menuAction())
        self.menuBar.addAction(self.menu.menuAction())
        self.menuBar.addAction(self.menu_2.menuAction())
        self.menuBar.addAction(self.menu_4.menuAction())
        self.menuBar.addAction(self.menu_5.menuAction())
        self.menuBar.addAction(self.menu_6.menuAction())
        self.menuBar.addAction(self.menu_7.menuAction())
        self.menuBar.addAction(self.menu_8.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Quinkokolobicky - "))
        self.menu.setTitle(_translate("MainWindow", "Входящие"))
        self.menu_2.setTitle(_translate("MainWindow", "Исходящие"))
        self.menu_3.setTitle(_translate("MainWindow", "Новое письмо"))
        self.menu_4.setTitle(_translate("MainWindow", "Спам"))
        self.menu_5.setTitle(_translate("MainWindow", "Корзина"))
        self.menu_6.setTitle(_translate("MainWindow", "Другие папки"))
        self.menu_7.setTitle(_translate("MainWindow", "Настройки аккаунта"))
        self.menu_8.setTitle(_translate("MainWindow", "Обновить"))
        self.action.setText(_translate("MainWindow", "Написать"))
        self.action_2.setText(_translate("MainWindow", "Использовать шаблон"))
        self.action_3.setText(_translate("MainWindow", "Скопировать из исходящих"))
        self.action_4.setText(_translate("MainWindow", "Открыть"))
        self.action_5.setText(_translate("MainWindow", "Очистить"))
        self.action_6.setText(_translate("MainWindow", "Отметить как прочтенное"))
        self.action_7.setText(_translate("MainWindow", "Открыть"))
        self.action_8.setText(_translate("MainWindow", "Очистить"))
        self.action_9.setText(_translate("MainWindow", "Переслать"))
        self.action_12.setText(_translate("MainWindow", "Открыть"))
        self.action_13.setText(_translate("MainWindow", "Добавить в ЧС нового абонента"))
        self.action_14.setText(_translate("MainWindow", "Удалить из ЧС абонента"))
        self.action_15.setText(_translate("MainWindow", "Очистить"))
        self.action_16.setText(_translate("MainWindow", "Открыть"))
        self.action_17.setText(_translate("MainWindow", "Очистить"))
        self.action_18.setText(_translate("MainWindow", "Открыть"))
        self.action_19.setText(_translate("MainWindow", "Добавить новую папку"))
        self.action_20.setText(_translate("MainWindow", "Удалить папку"))
        self.update_start.setText(_translate("MainWindow", "Запуск обновления"))
        self.updated_is.setText(_translate("MainWindow", "Проверка на новую версию"))

import resurs_rc
